export const PRODUCT_COPY = {
  landing: {
    title: "Products",
    backToCatalogLabel: "Back to catalog",
    loadingMessage: "Loading products...",
    fallbackErrorMessage: "Unable to load products.",
    emptyMessage: "No products are available right now.",
    emptyFilteredMessage: "No products match the selected filters.",
    catalogSelectLabel: "Catalog",
    emptyCatalogMessage: "No catalogs are available right now.",
    filtersTitle: "Filters",
    searchLabel: "Search",
    searchPlaceholder: "Search by name, code, or category",
    clearSearchLabel: "Clear search",
    clearFiltersLabel: "Clear filters",
    categoryFilterLabel: "Category",
    allCategoriesLabel: "All categories",
    uncategorizedLabel: "Uncategorized",
    resultCountLabel: "results",
    addToCartCtaLabel: "Add to cart",
    addingToCartCtaLabel: "Adding...",
    addToCartSuccessMessage: "Product added to cart.",
    missingQuoteWarningMessage: "No default quote available for your account.",
    addToCartPreconditionWarningMessage: "Product cannot be added because pricing details are missing.",
    addToCartMissingBillingFrequencyWarningMessage:
      "This product requires a billing frequency, but the API did not return a supported pricing term unit.",
    addToCartCommitmentUnsupportedWarningMessage:
      "This commitment-based product needs additional backend configuration before it can be added from this UI.",
    addToCartErrorMessage: "Unable to add product to cart.",
    bundleProductLabel: "Bundle",
    availabilityLabel: "Availability",
    notAvailableLabel: "Not available",
    priceLabel: "Price",
    activeLabel: "Active",
    inactiveLabel: "Inactive",
    detailsTitleFallback: "Product details",
    closeDetailsAriaLabel: "Close product details",
    imageGalleryTitle: "Product gallery",
    imageThumbnailAriaLabel: "View image",
    productDetailsLoadErrorMessage: "Unable to load full product details right now.",
    productDetailsUnavailableMessage: "Detailed product data is unavailable for this item.",
    categoryLabel: "Categories",
    attributesTitle: "Attributes",
    childItemsTitle: "Child items",
    childItemsQuantityLabel: "Quantity",
    attributeLabelLabel: "Label",
    defaultValueLabel: "Default value",
    statusLabel: "Status",
    noAttributesMessage: "Not available",
    noChildItemsMessage: "No child items are available for this product.",
    descriptionTitle: "Description",
    descriptionUnavailableLabel: "No description available.",
    nodeTypeLabel: "Node type",
    sellingModelsTitle: "Product selling model options",
    defaultOptionLabel: "Default",
    modelTypeLabel: "Selling model type",
    modelStatusLabel: "Model status",
    pricingTermLabel: "Pricing term",
    pricingTermUnitLabel: "Pricing term unit",
    autoRenewLabel: "Auto renew by default",
    yesLabel: "Yes",
    noLabel: "No",
    noSellingModelMessage: "No product selling model options available.",
  },
  catalog: {
    pageTitle: "Catalog Experience",
    pageSubtitle: "Browse, filter, and inspect Salesforce catalogs from a single workspace.",
    loadingMessage: "Loading catalogs...",
    fallbackErrorMessage: "Unable to load catalogs.",
    fallbackHelperMessage: "We could not reach the catalog service. Check your connection and try again.",
    emptyMessage: "No catalogs are available right now.",
    emptyFilteredMessage: "No catalogs match the current search and filter settings.",
    clearFiltersLabel: "Clear filters",
    clearSearchLabel: "Clear search",
    retryLabel: "Retry",
    searchLabel: "Search",
    searchPlaceholder: "Search by name, code, or description",
    typeFilterLabel: "Catalog type",
    allTypesLabel: "All types",
    sortLabel: "Sort by",
    resultCountLabel: "results",
    viewProductsCtaLabel: "View products",
    categoriesLabel: "Categories",
    codeLabel: "Code",
    startDateLabel: "Effective start",
    endDateLabel: "Effective end",
    totalCatalogsLabel: "Total catalogs",
    totalCategoriesLabel: "Total categories",
    datedCatalogsLabel: "Dated catalogs",
    undatedCatalogsLabel: "Undated catalogs",
    totalCatalogsHelper: "Catalog records returned by API",
    totalCategoriesHelper: "Combined categories across catalogs",
    datedCatalogsHelper: "Catalogs with effective dates",
    undatedCatalogsHelper: "Catalogs without effective dates",
    sortOptions: {
      nameAsc: "Name (A-Z)",
      nameDesc: "Name (Z-A)",
      categoriesDesc: "Categories (high-low)",
      categoriesAsc: "Categories (low-high)",
    },
  },
  dashboard: {
    title: "Executive Dashboard",
    subtitle: "High-level health across orders, quotes, assets, and account momentum.",
    lastUpdatedLabel: "Last updated",
    refreshTooltipLabel: "Refresh",
    createQuoteLabel: "Create New Quote",
    creatingQuoteLabel: "Creating...",
    missingIdentityWarningMessage: "Account identity is unavailable. Please retry RCA sync from settings.",
    createQuoteFailureWarningMessage: "Unable to create a default quote right now.",
    decisionRefreshWarningMessage: "Quote created, but active quote status could not be refreshed. Please try again.",
    missingActiveQuoteWarningMessage:
      "Quote created, but no active cart quote is available yet. Please refresh and try again.",
    createQuoteSuccessMessage: "Quote created successfully. Redirecting to cart.",
  },
  cart: {
    title: "Cart",
    quoteLabel: "Quote",
    missingQuoteWarning: "No default quote available for your account.",
    loadingMessage: "Loading cart details...",
    emptyCartMessage: "No items are available in your cart yet.",
    loadErrorMessage: "Unable to load cart details.",
    updateSuccessMessage: "Cart item updated.",
    removeSuccessMessage: "Cart item removed.",
    orderSuccessMessage: "Order created successfully.",
    orderErrorMessage: "Unable to create order from this quote.",
    missingLineIdWarning: "This cart line cannot be updated because its backend identifier is unavailable.",
    noChangesWarning: "No item changes were detected.",
    invalidInputWarning: "Please enter a valid quantity.",
    summaryTitle: "Summary",
    itemsTitle: "Items",
    placeOrderLabel: "Place order",
    fallbackTotalWarningMessage: "Total is estimated from quantity × unit price because server total was unavailable.",
    productLabel: "Product",
    quantityLabel: "Quantity",
    unitPriceLabel: "Unit price",
    lineTotalLabel: "Line total",
    actionsLabel: "Actions",
    saveLabel: "Save",
    removeLabel: "Remove",
    itemCountLabel: "Items",
    totalLabel: "Total",
  },
  checkout: {
    title: "Checkout",
    quoteLabel: "Quote",
    quoteFallbackLabel: "Unavailable",
    missingCheckoutStateMessage: "Checkout details are unavailable. Please return to cart and start again.",
    backToCartLabel: "Back to cart",
    orderReviewTitle: "Order review",
    contactTitle: "Contact information",
    billingTitle: "Billing information",
    shippingTitle: "Shipping information",
    sameAsBillingLabel: "Shipping address is same as billing",
    summaryTitle: "Order summary",
    quantityLabel: "Quantity",
    unitPriceLabel: "Unit price",
    lineTotalLabel: "Line total",
    itemCountLabel: "Items",
    totalLabel: "Total",
    fallbackTotalWarningMessage: "Total is estimated from quantity × unit price because server total was unavailable.",
    fullNameLabel: "Full name",
    emailLabel: "Email",
    countryCodeLabel: "Country code",
    phoneLabel: "Phone number",
    addressLine1Label: "Address line 1",
    addressLine2Label: "Address line 2 (optional)",
    cityLabel: "City",
    stateLabel: "State",
    postalCodeLabel: "Postal code",
    countryLabel: "Country",
    placeOrderLabel: "Place order",
    processingLabel: "Processing...",
    placeOrderSuccessMessage: "Order created successfully.",
    placeOrderErrorMessage: "Unable to create order from this quote.",
    queueUnavailableMessage:
      "Order request was accepted but queue status is unavailable. Please contact your administrator.",
    fullNameRequiredMessage: "Please enter your full name.",
    validEmailRequiredMessage: "Please enter a valid email address.",
    countryCodeRequiredMessage: "Please select a country code.",
    phoneRequiredMessage: "Please enter a phone number.",
    addressRequiredMessage: "Please enter address line 1.",
    cityRequiredMessage: "Please enter a city.",
    stateRequiredMessage: "Please enter a state.",
    postalCodeRequiredMessage: "Please enter a postal code.",
    countryRequiredMessage: "Please enter a country.",
  },
  orderStatus: {
    title: "Order status",
    quoteLabel: "Quote",
    jobLabel: "Job ID",
    processingMessage: "Checking order status...",
    completedMessage: "Order created successfully.",
    failedMessage: "Order processing failed. Please review checkout details and try again.",
    timeoutMessage: "Order status check timed out. Please return to checkout and retry.",
    missingStateMessage: "Order status details are unavailable. Start again from your cart.",
    unexpectedStatusMessage: "Order status is unavailable right now. Please contact your administrator.",
    backToCartLabel: "Back to cart",
    backToCheckoutLabel: "Back to checkout",
    retryStatusLabel: "Retry status check",
  },
  settings: {
    pageTitle: "Settings",
    pageSubtitle: "Manage your account details, security, and RCA access from one place.",
    accountSectionTitle: "Account",
    securityAccessSectionTitle: "Security & access",
    syncSectionTitle: "RCA profile sync",
    advancedDiagnosticsSectionTitle: "Advanced diagnostics",
    advancedDiagnosticsAccordionTitle: "View technical account details",
    appInfoSectionTitle: "App information",
    displayNameLabel: "Display name",
    emailLabel: "Email",
    providerLabel: "Auth provider",
    userIdLabel: "User ID",
    statusLabel: "Status",
    signedInStatus: "Signed in",
    unavailableValue: "Not available",
    profilePhotoAlt: "User profile photo",
    profilePhotoHelper: "Upload JPG, PNG, or WebP (max 2MB). Photo is stored on this browser only.",
    profilePhotoInputAriaLabel: "Upload profile photo",
    uploadPhotoCta: "Upload photo",
    removePhotoCta: "Remove photo",
    uploadPhotoSuccessMessage: "Profile photo updated.",
    uploadPhotoFallbackErrorMessage: "Unable to upload profile photo.",
    removePhotoSuccessMessage: "Profile photo removed.",
    removePhotoFallbackErrorMessage: "Unable to remove profile photo.",
    resetPasswordTitle: "Password reset",
    resetPasswordHelper: "Send a password reset link to your account email.",
    resetPasswordCta: "Send reset email",
    resetPasswordSuccessMessage: "Password reset email sent successfully.",
    resetPasswordMissingEmailMessage: "No email is available for this account.",
    resetPasswordFallbackErrorMessage: "Unable to send password reset email.",
    signOutTitle: "Sign out",
    signOutHelper: "End your current session on this device.",
    syncUnknownMessage: "No sync attempts have been recorded yet.",
    syncFailedMessage: "Profile sync failed. Retry to refresh your RCA identity.",
    syncSuccessMessage: "Profile sync is up to date.",
    syncStateUnknownLabel: "Unknown",
    syncStateFailedLabel: "Failed",
    syncStateSyncedLabel: "Synced",
    retrySyncCta: "Retry sync",
    retrySyncSuccessMessage: "Profile sync completed successfully.",
    retrySyncFallbackErrorMessage: "Profile sync is still failing.",
    decisionSectionTitle: "Decision status",
    activeQuoteLabel: "Active quote",
    activeOrderLabel: "Active order",
    activeAssetLabel: "Active asset",
    decisionActiveLabel: "Active",
    decisionInactiveLabel: "Inactive",
    lastAttemptLabel: "Last attempt",
    lastSuccessLabel: "Last success",
    lastFailureLabel: "Last failure",
    lastErrorLabel: "Last error",
    signOutCta: "Sign out",
    signOutSuccessMessage: "Signed out successfully.",
    signOutFallbackErrorMessage: "Unable to sign out.",
    versionLabel: "Version",
    legalLinkLabel: "Legal",
    contactLinkLabel: "Contact",
  },
  legal: {
    pageTitle: "Legal",
    pageSubtitle: "Review the privacy and terms policies for this app in one place.",
    lastUpdatedLabel: "Last updated",
    quickLinksTitle: "Quick links",
    privacySectionTitle: "Privacy",
    termsSectionTitle: "Terms",
    privacy: {
      pageTitle: "Privacy",
      pageSubtitle: "How we collect, use, and protect personal information when you use this app.",
      lastUpdated: "February 14, 2026",
      sections: [
        {
          title: "What we collect",
          body: "We collect account identity details and app usage events required to deliver authentication, customer support, and product browsing functionality.",
        },
        {
          title: "How we use data",
          body: "Data is used to operate services, secure your session, troubleshoot issues, and improve user experience. We do not sell personal information.",
        },
        {
          title: "Data retention",
          body: "We keep data only for as long as needed to meet product and legal requirements, then remove or anonymize it where possible.",
        },
      ],
    },
    terms: {
      pageTitle: "Terms",
      pageSubtitle: "The basic rules for using this app and related services responsibly.",
      lastUpdated: "February 14, 2026",
      sections: [
        {
          title: "Use of service",
          body: "You agree to use this app only for lawful business and customer operations and not to misuse APIs, content, or account access.",
        },
        {
          title: "Account responsibilities",
          body: "You are responsible for maintaining the confidentiality of your login credentials and for activity that occurs under your account.",
        },
        {
          title: "Service changes",
          body: "Features may be updated or retired over time. Continued use after updates indicates acceptance of the revised terms.",
        },
      ],
    },
    contact: {
      pageTitle: "Contact",
      pageSubtitle: "Reach our support team for account access, privacy requests, and general product questions.",
      lastUpdated: "February 14, 2026",
      form: {
        cardTitle: "Send us a message",
        cardSubtitle: "Share your request and our team will route it to the right owner.",
        fullNameLabel: "Full name",
        workEmailLabel: "Work email",
        topicLabel: "Topic",
        messageLabel: "Message",
        topicOptions: ["Account access", "Privacy request", "Product support", "General question"],
        submitLabel: "Submit request",
        consentNote: "By submitting this form, you agree that support may contact you about this request.",
      },
      supportPanel: {
        title: "Support details",
        availabilityTitle: "Business hours",
        responseTitle: "Response time",
        legalCtaLabel: "Open legal center",
      },
      sections: [
        {
          title: "Support email",
          body: "support@react-rca.dev",
        },
        {
          title: "Business hours",
          body: "Monday to Friday, 9:00 AM to 6:00 PM (local business time).",
        },
        {
          title: "Typical response time",
          body: "Most requests receive a response within one business day.",
        },
      ],
    },
  },
} as const;
