export const PRODUCT_COPY = {
  landing: {
    title: "Products",
    loadingMessage: "Loading products...",
    fallbackErrorMessage: "Unable to load products.",
    emptyMessage: "No products are available right now.",
    catalogSelectLabel: "Catalog",
    emptyCatalogMessage: "No catalogs are available right now.",
    productIdLabel: "Product ID",
    productCodeLabel: "Code",
    addToCartCtaLabel: "Add to cart",
    availabilityLabel: "Availability",
    notAvailableLabel: "Not available",
    activeLabel: "Active",
    inactiveLabel: "Inactive",
    detailsTitleFallback: "Product details",
    closeDetailsAriaLabel: "Close product details",
    categoryLabel: "Categories",
    sellingModelsTitle: "Product selling model options",
    defaultOptionLabel: "Default",
    modelTypeLabel: "Selling model type",
    modelStatusLabel: "Model status",
    pricingTermLabel: "Pricing term",
    pricingTermUnitLabel: "Pricing term unit",
    autoRenewLabel: "Auto renew by default",
    yesLabel: "Yes",
    noLabel: "No",
    noSellingModelMessage: "No product selling model options available.",
  },
  catalog: {
    pageTitle: "Catalog Experience",
    pageSubtitle: "Browse, filter, and inspect Salesforce catalogs from a single workspace.",
    loadingMessage: "Loading catalogs...",
    fallbackErrorMessage: "Unable to load catalogs.",
    fallbackHelperMessage: "We could not reach the catalog service. Check your connection and try again.",
    emptyMessage: "No catalogs are available right now.",
    emptyFilteredMessage: "No catalogs match the current search and filter settings.",
    clearFiltersLabel: "Clear filters",
    clearSearchLabel: "Clear search",
    retryLabel: "Retry",
    searchLabel: "Search",
    searchPlaceholder: "Search by name, code, or description",
    typeFilterLabel: "Catalog type",
    allTypesLabel: "All types",
    sortLabel: "Sort by",
    resultCountLabel: "results",
    detailsCtaLabel: "View details",
    categoriesLabel: "Categories",
    codeLabel: "Code",
    descriptionLabel: "Description",
    startDateLabel: "Effective start",
    endDateLabel: "Effective end",
    typeLabel: "Type",
    idLabel: "Catalog ID",
    metadataLabel: "Catalog metadata",
    overviewSectionLabel: "Overview",
    datesSectionLabel: "Dates",
    metadataSectionLabel: "Metadata",
    copyCorrelationIdLabel: "Copy correlation ID",
    copiedCorrelationIdMessage: "Correlation ID copied to clipboard.",
    copyCorrelationIdErrorMessage: "Unable to copy correlation ID.",
    noDataFallbackLabel: "Not available",
    closeDrawerAriaLabel: "Close catalog details",
    correlationIdLabel: "Correlation ID",
    totalCatalogsLabel: "Total catalogs",
    totalCategoriesLabel: "Total categories",
    datedCatalogsLabel: "Dated catalogs",
    undatedCatalogsLabel: "Undated catalogs",
    totalCatalogsHelper: "Catalog records returned by API",
    totalCategoriesHelper: "Combined categories across catalogs",
    datedCatalogsHelper: "Catalogs with effective dates",
    undatedCatalogsHelper: "Catalogs without effective dates",
    drawerTitleFallback: "Catalog details",
    sortOptions: {
      nameAsc: "Name (A-Z)",
      nameDesc: "Name (Z-A)",
      categoriesDesc: "Categories (high-low)",
      categoriesAsc: "Categories (low-high)",
    },
  },
  settings: {
    pageTitle: "Settings",
    pageSubtitle: "Manage your account details and session access.",
    profileSectionTitle: "Profile",
    securitySectionTitle: "Security",
    sessionSectionTitle: "Session",
    appInfoSectionTitle: "App information",
    displayNameLabel: "Display name",
    emailLabel: "Email",
    providerLabel: "Auth provider",
    userIdLabel: "User ID",
    statusLabel: "Status",
    signedInStatus: "Signed in",
    unavailableValue: "Not available",
    resetPasswordTitle: "Password reset",
    resetPasswordHelper: "Send a password reset link to your account email.",
    resetPasswordCta: "Send reset email",
    resetPasswordSuccessMessage: "Password reset email sent successfully.",
    resetPasswordMissingEmailMessage: "No email is available for this account.",
    resetPasswordFallbackErrorMessage: "Unable to send password reset email.",
    signOutCta: "Sign out",
    signOutSuccessMessage: "Signed out successfully.",
    signOutFallbackErrorMessage: "Unable to sign out.",
    versionLabel: "Version",
    legalLinkLabel: "Legal",
    contactLinkLabel: "Contact",
  },
  legal: {
    pageTitle: "Legal",
    pageSubtitle: "Review the privacy and terms policies for this app in one place.",
    lastUpdatedLabel: "Last updated",
    quickLinksTitle: "Quick links",
    privacySectionTitle: "Privacy",
    termsSectionTitle: "Terms",
    privacy: {
      pageTitle: "Privacy",
      pageSubtitle: "How we collect, use, and protect personal information when you use this app.",
      lastUpdated: "February 14, 2026",
      sections: [
        {
          title: "What we collect",
          body: "We collect account identity details and app usage events required to deliver authentication, customer support, and product browsing functionality.",
        },
        {
          title: "How we use data",
          body: "Data is used to operate services, secure your session, troubleshoot issues, and improve user experience. We do not sell personal information.",
        },
        {
          title: "Data retention",
          body: "We keep data only for as long as needed to meet product and legal requirements, then remove or anonymize it where possible.",
        },
      ],
    },
    terms: {
      pageTitle: "Terms",
      pageSubtitle: "The basic rules for using this app and related services responsibly.",
      lastUpdated: "February 14, 2026",
      sections: [
        {
          title: "Use of service",
          body: "You agree to use this app only for lawful business and customer operations and not to misuse APIs, content, or account access.",
        },
        {
          title: "Account responsibilities",
          body: "You are responsible for maintaining the confidentiality of your login credentials and for activity that occurs under your account.",
        },
        {
          title: "Service changes",
          body: "Features may be updated or retired over time. Continued use after updates indicates acceptance of the revised terms.",
        },
      ],
    },
    contact: {
      pageTitle: "Contact",
      pageSubtitle: "Reach our support team for account access, privacy requests, and general product questions.",
      lastUpdated: "February 14, 2026",
      form: {
        cardTitle: "Send us a message",
        cardSubtitle: "Share your request and our team will route it to the right owner.",
        fullNameLabel: "Full name",
        workEmailLabel: "Work email",
        topicLabel: "Topic",
        messageLabel: "Message",
        topicOptions: ["Account access", "Privacy request", "Product support", "General question"],
        submitLabel: "Submit request",
        consentNote: "By submitting this form, you agree that support may contact you about this request.",
      },
      supportPanel: {
        title: "Support details",
        availabilityTitle: "Business hours",
        responseTitle: "Response time",
        legalCtaLabel: "Open legal center",
      },
      sections: [
        {
          title: "Support email",
          body: "support@react-rca.dev",
        },
        {
          title: "Business hours",
          body: "Monday to Friday, 9:00 AM to 6:00 PM (local business time).",
        },
        {
          title: "Typical response time",
          body: "Most requests receive a response within one business day.",
        },
      ],
    },
  },
} as const;
