export const PRODUCT_COPY = {
  landing: {
    title: "Catalogs",
    loadingMessage: "Loading catalogs...",
    fallbackErrorMessage: "Unable to load catalogs.",
    emptyMessage: "No catalogs are available right now.",
  },
  catalog: {
    pageTitle: "Catalog Experience",
    pageSubtitle: "Browse, filter, and inspect Salesforce catalogs from a single workspace.",
    loadingMessage: "Loading catalogs...",
    fallbackErrorMessage: "Unable to load catalogs.",
    fallbackHelperMessage: "We could not reach the catalog service. Check your connection and try again.",
    emptyMessage: "No catalogs are available right now.",
    emptyFilteredMessage: "No catalogs match the current search and filter settings.",
    clearFiltersLabel: "Clear filters",
    clearSearchLabel: "Clear search",
    retryLabel: "Retry",
    searchLabel: "Search",
    searchPlaceholder: "Search by name, code, or description",
    typeFilterLabel: "Catalog type",
    allTypesLabel: "All types",
    sortLabel: "Sort by",
    resultCountLabel: "results",
    detailsCtaLabel: "View details",
    categoriesLabel: "Categories",
    codeLabel: "Code",
    descriptionLabel: "Description",
    startDateLabel: "Effective start",
    endDateLabel: "Effective end",
    typeLabel: "Type",
    idLabel: "Catalog ID",
    metadataLabel: "Catalog metadata",
    overviewSectionLabel: "Overview",
    datesSectionLabel: "Dates",
    metadataSectionLabel: "Metadata",
    copyCorrelationIdLabel: "Copy correlation ID",
    copiedCorrelationIdMessage: "Correlation ID copied to clipboard.",
    copyCorrelationIdErrorMessage: "Unable to copy correlation ID.",
    noDataFallbackLabel: "Not available",
    closeDrawerAriaLabel: "Close catalog details",
    correlationIdLabel: "Correlation ID",
    totalCatalogsLabel: "Total catalogs",
    totalCategoriesLabel: "Total categories",
    datedCatalogsLabel: "Dated catalogs",
    undatedCatalogsLabel: "Undated catalogs",
    totalCatalogsHelper: "Catalog records returned by API",
    totalCategoriesHelper: "Combined categories across catalogs",
    datedCatalogsHelper: "Catalogs with effective dates",
    undatedCatalogsHelper: "Catalogs without effective dates",
    drawerTitleFallback: "Catalog details",
    sortOptions: {
      nameAsc: "Name (A-Z)",
      nameDesc: "Name (Z-A)",
      categoriesDesc: "Categories (high-low)",
      categoriesAsc: "Categories (low-high)",
    },
  },
  settings: {
    pageTitle: "Settings",
    pageSubtitle: "Manage your account details and session access.",
    profileSectionTitle: "Profile",
    securitySectionTitle: "Security",
    sessionSectionTitle: "Session",
    appInfoSectionTitle: "App information",
    displayNameLabel: "Display name",
    emailLabel: "Email",
    providerLabel: "Auth provider",
    userIdLabel: "User ID",
    statusLabel: "Status",
    signedInStatus: "Signed in",
    unavailableValue: "Not available",
    resetPasswordTitle: "Password reset",
    resetPasswordHelper: "Send a password reset link to your account email.",
    resetPasswordCta: "Send reset email",
    resetPasswordSuccessMessage: "Password reset email sent successfully.",
    resetPasswordMissingEmailMessage: "No email is available for this account.",
    resetPasswordFallbackErrorMessage: "Unable to send password reset email.",
    signOutCta: "Sign out",
    signOutSuccessMessage: "Signed out successfully.",
    signOutFallbackErrorMessage: "Unable to sign out.",
    versionLabel: "Version",
    privacyLinkLabel: "Privacy",
    termsLinkLabel: "Terms",
    contactLinkLabel: "Contact",
  },
} as const;
