export const ROUTES = {
  home: "/",
  login: "/login",
  logout: "/logout",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  contact: "/contact",
  terms: "/terms",
  privacy: "/privacy",
  catalog: "/catalog",
  dashboard: "/dashboard",
  products: "/products",
  productDetail: "/products/:id",
  cart: "/cart",
  checkout: "/checkout",
  settings: "/settings",
} as const;
